import assert from 'node:assert/strict';
import path from 'node:path';
import {monitor} from '../scripts/paths.mjs';
const {evaluate,summaries,accountSummaries}=await import(path.join(monitor,'assets/model.mjs'));
const t={id:'test',tradeDate:'2026-01-01',status:'在期',currency:'USD',amount:100000,productType:'FCN',ko:1,maturityDate:'2026-12-01',observationDates:['2026-02-02','2026-03-02'],underlyings:[{symbol:'A',initial:100},{symbol:'B',initial:100}],rule:{verified:true,source:'test termsheet',koEnabled:true,levelVerified:true,scheduleVerified:true,mode:'離散全數',comparison:'>='}};
const d={expectedPriceDate:'2026-03-02',prices:{A:{'2026-02-02':{close:100},'2026-03-02':{close:90}},B:{'2026-02-02':{close:90},'2026-03-02':{close:100}}}};
const copy=x=>structuredClone(x),run=(tt,dd=d)=>evaluate(tt,dd);
assert.equal(run(t).code,'clear');
let m=copy(t);m.rule.mode='記憶KO';assert.equal(run(m).code,'candidate');
let both=copy(d);both.prices.B['2026-02-02'].close=100;assert.equal(run(t,both).date,'2026-02-02');
m=copy(t);m.rule.comparison='>';assert.equal(run(m,both).code,'clear');
m=copy(t);m.rule.verified=false;assert.equal(run(m,both).code,'potential');
m.rule.scheduleVerified=false;assert.equal(run(m,both).code,'blocked');
m=copy(t);m.rule.koEnabled=false;assert.equal(run(m).code,'no-ko');
m=copy(t);m.ko=null;assert.equal(run(m).code,'blocked');
let missing=copy(d);delete missing.prices.B['2026-02-02'];assert.equal(run(t,missing).code,'blocked');
m=copy(t);m.rule.mode='每日全數';assert.equal(run(m).code,'blocked');
let daily=copy(d);daily.tradingDays=['2026-02-02','2026-02-03','2026-03-02'];assert.equal(run(m,daily).code,'blocked');
m=copy(t);m.underlyings[0].symbol=null;assert.equal(run(m).code,'blocked');
m=copy(t);m.status='提前敲出';assert.equal(run(m).code,'closed');
m=copy(t);m.observationDates=['2026-04-01'];assert.equal(run(m).code,'waiting');
const s=summaries([t,{...t,id:'JPY',currency:'JPY',amount:1e7},{...t,id:'Q2',tradeDate:'2026-04-01',amount:50000}],2026,'USD');
assert.equal(s.total,150000);assert.equal(s.selected.length,2);assert.equal(s.quarterly[0].amount,100000);assert.equal(s.quarterly[1].amount,50000);
const accounts=accountSummaries([{...t,clientCode:'A'},{...t,id:'2',clientCode:'A',amount:50000},{...t,id:'3',clientCode:'B',amount:70000,status:'到期'}],d,'2026-03-03');
assert.equal(accounts.length,2);assert.equal(accounts[0].amount,150000);assert.equal(accounts[0].count,2);assert.equal(accounts[1].openAmount,0);assert.equal(accounts.reduce((n,a)=>n+a.amount,0),220000);
m=copy(t);m.rule.mode='每日記憶KO';daily=copy(d);daily.tradingDays=['2026-02-02','2026-03-02'];assert.equal(run(m,daily).code,'candidate');
console.log('帳戶及 14 組核心邊界驗證通過：等值、記憶、日期、缺價、幣別與狀態。');
